# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 14.19.3 --chrome=105.0.5195.52 --firefox=104.0
set e+x

LOCAL_NAME=cypress/browsers:node14.19.3-chrome105-ff104
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
